server:
  port: 8080

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: false

      routes:
        - id: reserva
          uri: lb://servico-reserva
          predicates:
            - Path=/reservas/**

        - id: pagamento
          uri: lb://servico-pagamento
          predicates:
            - Path=/pagamentos/**

        - id: catraca
          uri: lb://servico-catraca
          predicates:
            - Path=/catraca/**

        - id: acesso
          uri: lb://servico-acesso
          predicates:
            - Path=/acesso/**

eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka
  instance:
    prefer-ip-address: true
