server:
  port: 8080

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: reserva
          uri: lb://servico-reserva
          predicates:
            - Path=/reservas/**

        - id: pagamento
          uri: lb://servico-pagamento
          predicates:
            - Path=/pagamentos/**

        - id: catraca
          uri: lb://servico-catraca
          predicates:
            - Path=/catraca/**

        - id: acesso
          uri: lb://servico-acesso
          predicates:
            - Path=/acesso/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
