server.port=8083
spring.application.name=servico-catraca

# Configuração do Service Discovery (Eureka)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Força o serviço a se registrar usando o endereço IP (evita problemas de rede no Windows)
eureka.instance.prefer-ip-address=true