# Porta e Identificação no Eureka
server.port=8082
spring.application.name=servico-pagamento

# Configuração do Banco de Dados H2 (Exclusivo do Pagamento)
spring.datasource.url=jdbc:h2:mem:pagamentodb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

# Registro no Service Discovery
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true