server.port=8761
spring.application.name=service-discovery

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.instance.hostname=service-discovery
eureka.server.wait-time-in-ms-when-sync-empty=0
